### PR TITLE
Error on no Scenario for Task Helpers

### LINKED ISSUE #230: Issue clearer error messages if no scenario
For task and hint related helpers, issue an error message like "you have not started a scenario" if there is no scenario. Currently the error message is just "error:	Cannot read property '1' of undefined"

### PR DESCRIPTION
**Pull request by s-irvine**
Fixes #230 

I had to also update the conditional error for the `next_hint` and `show_hint` helpers. I think this due to changes in e325d0520a13698b8a93dad61552077e66ccfef4.

### CODE REVIEW

File: tools/scenario-tools/lib/tasks.js [hunk 1]
```diff
@@ -90,6 +90,11 @@ async function processTask (newTask, taskspath = TASKS_FILE_PATH,
   progresspath = PROGRESS_FILE_PATH, log = logger) {
   const { name, tasks } = loadYamlFile(taskspath)
 
+  if (tasks === undefined) {
+    logger.error('A scenario cannot be found! Has one been provisioned with `simulator scenario launch ...`?')
+    process.exit(1)
```
Comment (raoulmillais) [inline tools/scenario-tools/lib/tasks.js:95]: We should `throw new Error(<message>)` here and not log an error and use `process.exit` that will keep the responsibility of exiting the process in one place in `bin/process_task.js`

File: tools/scenario-tools/test/tasks_test.js [hunk 2]
```diff
@@ -348,3 +348,29 @@ test('startTask updates current_task and scores if answer is yes', async t => {
...
+  } catch (e) {
+    t.is(e.message, 'A scenario cannot be found! Has one been provisioned with `simulator scenario launch ...` ?')
+    return t.pass()
+  }
+  t.fail('processTask did not throw')
+})
+
+test('processTask errors when tasks.yaml does not contain YAML', async t => {
+  const progress = fixture('progress.json')
+  const tasks = fixture('tasks-empty.yaml')
```
Comment (raoulmillais) [inline tools/scenario-tools/test/tasks_test.js:367]: Both these tests are using the same yaml file.  This should be `tasks-no-task.yaml`
